---
- name: Socle commun, durcissement et Docker
  hosts: all
  become: true
  roles:
    - common
    - hardening
    - docker

- name: Serveur CI/CD
  hosts: ci_servers
  become: true
  roles:
    - jenkins
